(package
  (name "")
  (version 0.1)
  (license "BSD")
  (authors "")
  (maintainers "")
  (description "")
  (tags "")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/____")
  (test "test.scm")
  (dependencies ())
  (test-dependencies ())
  (foreign-dependencies ())
  (library (name ____) (description ""))
  (program (name ____) (description "")))
